package-lock.json
src/components/App.js
src/components/Himadri.js

Added my name

---

package.json
src/components/Home.spec.js

deployment

---

.travis.yml
package-lock.json
package.json

make travis run surge

---

src/components/Ally.js
src/components/App.js

ally first commit

---

.travis.yml

try again with surge

---

.travis.yml

deployment w surge take #4

---

src/components/App.js

fix linting error

---

src/components/App.js

emma's branch commit

---

package-lock.json
package.json
src/actions/index.js
src/components/Home.js
src/reducers/initialState.js
src/reducers/userReducer.js

translate spotify data to our schema

---

src/components/GenreChart/index.js
src/components/Home.js
src/styles/styles.scss
src/utils/spotifyUtils.js

build genre chart

---

src/components/Dashboard/Histogram.js
src/styles/styles.scss

style histogram

---

src/components/App.js
src/styles/styles.scss

make sidebar sticky

---

src/components/Compare/index.js
src/components/Compare/style.scss
src/components/Dropdown/style.scss
src/components/Era/index.js
src/components/Era/style.scss
src/components/GenreChart/index.js
src/components/GenreChart/style.scss
src/components/Histogram/style.scss
src/components/Me/index.js
src/components/Me/style.scss
src/components/Sidebar/style.scss
src/components/SpiderGraph/index.js
src/components/SpiderGraph/style.scss
src/components/Trendex/index.js
src/components/Trendex/style.scss
src/styles/base.scss

Styling of compare and profile dashboards

---

src/components/AuthRedirect/index.js
src/components/Compare/index.js
src/components/Histogram/index.js

overlay histogram

---

src/components/Compare/index.js
src/components/GenreChart/index.js
src/components/Me/index.js

fix genre chart bug

---

package-lock.json
package.json
src/components/Login/style.scss
src/components/Sidebar/index.js
src/components/Sidebar/style.scss

Adding "add friend" action flow

---

package-lock.json
package.json
src/components/Survey/index.js
src/components/Survey/style.scss
src/styles/styles.scss

Scaffold for surveypage

---

src/components/Login/index.js
src/components/Sidebar/index.js
src/components/Sidebar/style.scss

under construction and some links done

---

src/components/Dropdown/index.js
src/components/Survey/index.js
src/components/Survey/style.scss

styling survey

---

src/components/Survey/index.js
src/components/Survey/style.scss

fixed dropdowns

---

src/actions/index.js
src/components/Compare/index.js
src/components/Sidebar/index.js
src/constants/actionTypes.js
src/reducers/friendReducer.js
src/reducers/initialState.js
src/reducers/userReducer.js
src/utils/backendUtils.js

sidebar now adds friends

---

src/components/Survey/index.js
src/components/Survey/style.scss

hardcoded date to hook up to backend

---

src/components/Dropdown/index.js
src/components/SpiderGraph/index.js
src/styles/base.scss

dropdown bug

---

src/actions/index.js
src/components/Sidebar/index.js
src/constants/actionTypes.js
src/reducers/authReducer.js
src/reducers/userReducer.js

Logout button working and redirecting

---

src/components/Survey/index.js

fix props for survey

---

src/components/Survey/index.js

added dropdown options

---

src/components/App.js
src/components/Survey/index.js

country and region survey q

---

src/components/App.js
src/components/Dropdown/style.scss
src/components/Survey/index.js
src/components/Survey/style.scss

survey displays

---

package-lock.json
package.json
src/components/App.js
src/components/MultiDropdown/index.js
src/components/Survey/index.js
src/components/Survey/style.scss

Polishsurvey

---

src/actions/index.js
src/components/App.js
src/components/Dashboard/index.js
src/components/Sidebar/index.js
src/components/Survey/index.js
src/components/Trendex/index.js
src/constants/surveyOptions.js
src/utils/backendUtils.js

connect survey

---

src/components/SpiderGraph/index.js

remove attribute labels for spidergraph compare

---

src/components/Compare/index.js

Reverts dartmouth-cs98/duet-client#50

Revert "Added key"

---

package-lock.json
package.json
src/components/Sidebar/index.js
src/components/Sidebar/style.scss

images are now built by webpack

---

src/actions/index.js
src/components/Sidebar/index.js
src/reducers/initialState.js

fix add first friend bug

---

src/components/Compare/index.js
src/components/Compare/style.scss
src/components/Histogram/index.js
src/components/Login/index.js
src/components/Login/style.scss
src/components/SpiderGraph/index.js

Fix styling for chart comparison key

---

src/components/DataStories/Decades/index.js
src/components/DataStories/HeatMap/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/TopGenres/index.js
src/components/DataStories/Trendex/index.js
src/components/Page/index.js
src/components/Story/index.js
src/styles/styles.scss

data story scaffold

---

src/components/OtherStories/Compare/index.js
src/components/OtherStories/Info/index.js
src/components/OtherStories/Members/index.js
src/components/OtherStories/Share/index.js
src/components/Story/index.js

Make pages into components

---

src/components/DataStories/Trendex/index.js
src/components/DataStories/Trendex/style.scss
src/components/OtherStories/Share/index.js
src/components/OtherStories/Share/style.scss

Text a friend working

---

src/components/OtherStories/Members/index.js
src/components/Page/index.js

Re-style progress bar

---

package-lock.json
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/MusicalAttr/style.scss
src/components/DataStories/TopGenres/index.js
src/components/Page/style.scss
src/components/Story/index.js
src/components/Story/style.scss
src/reducers/compareReducer.js
src/reducers/index.js
src/reducers/initialState.js
src/styles/styles.scss

redid component, so we can plug in data

---

src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/MusicalAttr/style.scss
src/components/DataStories/Trendex/index.js

histogram page style

---

src/components/DataStories/TopArtists/index.js
src/components/DataStories/TopArtists/style.scss
src/components/DataStories/Trendex/index.js
src/components/DataStories/Trendex/style.scss
src/styles/base.scss

make top artists responsive

---

src/components/App.js
src/components/DataStories/Decades/style.scss

slight styling changes for decades

---

src/components/DataStories/TopArtists/index.js

added user name

---

src/actions/index.js
src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/TopGenres/index.js
src/components/DataStories/Trendex/index.js
src/types/index.js
src/utils/backendUtils.js
src/utils/spotifyUtils.js

small udpates to genres

---

src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/TopGenres/index.js
src/components/DataStories/Trendex/index.js
src/components/Page/index.js

fixed top bar to 5

---

src/actions/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopGenres/index.js
src/components/Story/index.js

Fixing emmas mistake

---

src/utils/backendUtils.js

Join group working

---

src/components/OtherStories/Compare/index.js

Bug fix for adding group

---

src/actions/index.js
src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js

graph axises match now

---

src/actions/index.js
src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/Trendex/index.js
src/components/Story/index.js
src/constants/actionTypes.js
src/reducers/usersReducer.js

Added you when you are comparing yourself

---

src/actions/index.js
src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/Trendex/index.js
src/components/Story/index.js
src/constants/actionTypes.js
src/reducers/usersReducer.js

zac various updates

---

src/components/OtherStories/Compare/index.js
src/components/OtherStories/Members/index.js

Lowercase search bug fix

---

src/actions/index.js
src/components/DataStories/Decades/index.js
src/components/DataStories/MusicalAttr/index.js
src/components/DataStories/TopArtists/index.js
src/components/DataStories/Trendex/index.js
src/components/Story/index.js
src/constants/actionTypes.js
src/reducers/usersReducer.js

Put the name changes back

---

src/components/OtherStories/Compare/index.js

I'm so sorry

---

src/actions/index.js
src/components/InfoAndCompare/Compare/index.js
src/components/Stories/MusicalAttr/index.js
src/components/Stories/PlaylistGenerator/index.js
src/components/Stories/index.js
src/constants/actionTypes.js
src/reducers/authReducer.js
src/utils/playlistGenerator.js

generate optimal playlist stuff

---

package-lock.json
package.json
src/components/Stories/Decades/index.js
src/components/Stories/Decades/style.scss
src/components/Stories/TopArtists/index.js
src/components/Stories/TopArtists/style.scss
src/components/Stories/Trendex/index.js
src/components/Stories/Trendex/style.scss

* Fix styling on pop-ups and fix scroll bug
* Make the ? button on pages responsive (I don't know how to do this)
* Move the pop-up into a separate component
* Compare page looks funky
* Actually write the about pop-ups
:heart:

Fixed styling 1, 2, 5 and added pop-ups

---

src/components/Page/index.js
src/components/Stories/Decades/index.js
src/components/Stories/MusicalAttr/index.js
src/components/Stories/TopArtists/index.js
src/components/Stories/TopGenres/index.js
src/components/Stories/Trendex/index.js
src/components/Stories/index.js
src/components/Stories/style.scss

fix pagination bar on top:

---

src/components/Stories/MusicalAttr/index.js
src/components/Stories/MusicalAttr/style.scss

add key to taste page

---

src/components/Compare/index.js
src/components/Stories/index.js

toggles now do stuff

---

src/actions/index.js
src/components/App.js
src/components/Compare/index.js
src/components/Compare/style.scss
src/components/Login/index.js
src/components/Search/index.js
src/components/Search/style.scss
src/styles/styles.scss

build search bar

---

src/components/Stories/TopArtists/index.js
src/components/Stories/TopArtists/style.scss

name bug and color fix

---

src/actions/index.js
src/components/Compare/index.js

Zaccccc branch

---

src/components/Popup/style.scss
src/components/Stories/Decades/style.scss
src/components/Stories/TopArtists/index.js
src/components/Stories/TopArtists/style.scss
src/components/Stories/TopGenres/index.js
src/components/Stories/TopGenres/style.scss
src/constants/helpInfo.js

Popup Descriptions!

---

src/components/Stories/Blender/index.js
src/components/Stories/Members/index.js
src/components/Stories/Members/style.scss
src/components/Stories/index.js
src/utils/backendUtils.js

Showing real names!

---

src/components/Compare/index.js
src/utils/backendUtils.js

addGroupModal

---

src/components/Login/style.scss
src/images/squigs.svg

Added squigs and borders on front page

---

src/components/Compare/index.js
src/components/Compare/style.scss
src/utils/backendUtils.js

checkbox to make group private

---

src/components/App.js
src/components/Compare/index.js
src/components/Login/index.js
tools/authServer.js

Sharing link

---

src/components/Login/index.js
src/components/Login/style.scss

fixed learn more pop-up

---

src/components/Popup/index.js
src/components/Stories/index.js
src/constants/helpInfo.js

switched members screen order

---

src/components/Compare/index.js
src/components/ShareModal/index.js
src/components/ShareModal/style.scss
src/components/Stories/Blender/index.js
src/components/Stories/Members/index.js
src/components/Stories/Share/index.js
src/components/Stories/Share/style.scss
src/reducers/usersReducer.js
src/styles/styles.scss

Sharing updates

---

package-lock.json
package.json
src/components/ShareModal/index.js
src/components/ShareModal/style.scss

Copy fix for mobile

---

src/components/Login/index.js

fix join group bug

---

src/components/Stories/index.js
tools/authServer.js

remove list of names

---

src/components/Stories/index.js

progress bar fix
